### ISSUE TITLE
Heads up, we've added an Active sort in the release today.

### ISSUE THREAD

**Issue by dessalines** [IronOxidizer/lemmy-lite#4]
[Here's the full changes](https://github.com/LemmyNet/lemmy/blob/main/RELEASES.md#lemmy-v0740-pre-release-2020-08-05), but we've added an Active sort, I noticed lemmy-lite has that dropdown.

**Comment by IronOxidizer** [comment]
I'll get this implemented in lemmy-lite sometime this week. Thanks for letting me know!

**Comment by IronOxidizer** [comment]
Implemented and live at https://lemmylite.crabdance.com
